TRAINING_FILE = "../input/train_data_2000.csv"
CONTACT_FILE = "../input/contact_data_2000.csv"
TEST_FILE = "../input/test_data_2000.csv"
MODEL_OUTPUT = "../models/"
PROCESSED_TRAIN_OUTPUT = "../input/processed_train.csv"
PROCESSED_TEST_OUTPUT = "../input/processed_test.csv"